import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ErrorWrapper from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: 'Next.js Tuturial - Codevolution',
    template: '%s | Codevolution',
  },
  description: "Generated by create next app",
};

export default function GeneralLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{
          backgroundColor: "lightblue",
          padding: "1rem",
          color: "black",
        }}>
          <p>Header</p>
        </header>
        <h1>General</h1>
        <ErrorWrapper>{children}</ErrorWrapper>
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            color: "black",
          }}
        >
          <p>
            Footer
          </p>
        </footer>
      </body>
    </html>
  );
}
